### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by andrij-git** [andrij-git/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by for-web-an** [comment]
Ще можна додати розділ "Інформація від замовника", в якому зберігається надана та затверджена в той чи інший спосіб замовником логотип компанії, слогани, фотографії тощо.

**Comment by andrij-git** [comment]
Це точно. Надай пропозиції щодо механізмів реалізації.
